### ISSUE TITLE
Request to make ForceApi extendable

### ISSUE THREAD

**Issue by ykoer** [jesperfj/force-rest-api#14]
I would like to extend ForceApi to call custom salesforce apex rest api's.
Could you please change session and apiRequest access modifiers to protected?

**Comment by jesperfj** [comment]
@ykoer & @alexsapps: would love to support this request if it's still relevant to you, or close this issue if you've moved on. Seeing some sample code of what you have in mind would be great.

**Comment by alexsapps** [comment]
hey @jesperfj, in my fork i added the ability to create custom commands (like the chatter api) while trying somewhat to maintain backward compatibility.  only the parts that i was using are tested however.  see here if you're interested:
https://github.com/alexsapps/force-rest-api/tree/improvementsMarch2015

**Comment by alexsapps** [comment]
i'm curious what you think about it too, but i can't invest much time to fix anything right now unfortunately.  thanks again for this api -- it was very useful while i was working on a gus integration for the db schema team :)

**Comment by jesperfj** [comment]
Took a look at your fork. Lots of interesting stuff in there. Probably way too much to ever try to merge back into this library.

It's probably better to figure out how this library can be used as part of a composition. Perhaps I need to cut it down to just the Auth and other basic parts (the request/response logic) and factor the REST API calls into another lib.

**Comment by alexsapps** [comment]
sure, sounds good to me.  would it have helped if i told you about my fork
earlier or still would've been too much?  i wasnt sure, and then i forgot,
subconsciously assuming people look at the github fork tree. i am new to
this stuff so any tips glady accepted.  hahah.

hmm, two libs is potentially unnecessary compexity too since the outer lib
won't have much.  the chatter api for example is one lib, extensible and
provides command classes for the most basic operations.

thanks!

**Comment by jesperfj** [comment]
It would probably have helped if you had submitted pull requests along the way for your various improvements. I am not sure at all if splitting up this library is the best idea. It's just a thought I had and as you can tell, I haven't taken any action on it so far :-). I've been pretty lenient with accepting contributions because I don't have much time to work on this myself and I don't know that this library has critical customers with strong requirements for stability.

**Comment by jesperfj** [comment]
I took a stab at a possible approach to make it more extensible in #24. Would love your feedback. I moved apiRequest() to ApiSession. uriBase() still seems like just a utility method specific to ForceApi so I didn't move it.

**Comment by jesperfj** [comment]
@ykoer and @alexsapps, take a look at #41 and release 0.0.35 and see if it meets your use cases.

**Comment by jesperfj** [comment]
Closing this. Reopen if you have more feedback.

**Comment by quintencls** [comment]
Hi @jesperfj First of all, thanks writing the library!

I would also like to use it to make a call to a custom apex endpoint. But these have a path like the following: `/services/apexrest/...`.

The lowest level `public` method I can find in the `ForceApi` class is the `request()` method, this one still prepends `/services/data/<version>` to the path that it is given.

Maybe you could add a method similar to this: `apexRequest(String method, String path, Object input)`? That would prepend the given path with `/services/apexrest` and use the `private apiRequest(HttpRequest req)` method to make the authenticated call.

It's just an idea after a quick look at the code.
