### ISSUE TITLE
JDK 8, mvn install -DskipTests is failing.

### ISSUE THREAD

**Issue by anishsatalkar** [jesperfj/force-rest-api#88]
### Environment
JDK: 1.8

### Issue
After cloning the project and running `mvn install -DskipTests`, it is failing with the error `class file for org.eclipse.jetty.util.component.aggregatelifecycle not found` while compiling the file `EndToEndOAuthFlowExample.java` at line 131. 

### Resolution
After adding the dependency https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-util/8.1.14.v20131031 to `pom.xml`, the issue was resolved.

Is there anything I am missing here?

**Comment by jesperfj** [comment]
Wow. Interesting. I was happily running tests in my local environment until I ran a `mvn clean` and then I got the same error you got. I have no idea why it's suddenly necessary to include jetty-util. But as you say, it does the trick. If these were runtime dependencies I'd be more worried, but since they're only test dependencies, I am not going to fuss much over it. I've added jetty-util to the test deps.
